plugins:
  orphan_crawler_signature:
    default: ""
    type: string
    textarea: true
    client: false

  orphan_og_locale:
    default: "en_CA"
    type: string
    client: false

  orphan_index_min_topics:
    default: 5
    type: integer
    min: 0
    client: false
